### ISSUE TITLE
Questions about the current state of the package

### ISSUE THREAD

**Issue by Relrin** [Nebo15/rbmq#11]
Hello,

I'm curious about using this package in my own project, but noticed that the package isn't updated a long time ago and doesn't developing further. So, I have a couple of questions related to the package:

- Do you have any plans to support this project? It not also related to the adding functionality, but updating the requirements as well (for example, the `amqp` package which is actively it using).
- If the project is being no longer supported, then can I reuse some pieces of this codebase in a custom package? But of course, in this case I should to mention about re-using the code from this library. Perhaps in AUTHORS file in the custom package? Or maybe somewhere else?

**Comment by AndrewDryga** [comment]
Hello @Relrin,

This package is not actively maintained, but I plan to release a completely new version or even a new package based on similar principles (but with a more mature code which is actively used in production). I would not recommend using this one as-is. (You can try to take a look at gen_queue and task_bunny.)

Feel free to reuse any code pieces, simple notice in the bottom of readme would be more than enough :).

**Comment by Relrin** [comment]
Ok, got it. Thank you for the detailed answer!

**Comment by AndrewDryga** [comment]
You're welcome. Subscribe to the repo if you don't want to miss new release :).
